[package]
name = "erpc-analysis"
version = "0.1.0"
edition = "2021"
rust-version = "1.77"

[dependencies]
anyhow.workspace = true
futures.workspace = true
neo4rs.workspace = true
petgraph.workspace = true
serde_json.workspace = true
serde.workspace = true
tokio.workspace = true
