[book]
title = "eRPC Documentation"

language = "en"
multilingual = false
src = "src"

[output.html]
default-theme = "light"
curly-quotes = true
mathjax-support = false
additional-css = []
additional-js = []

[output.html.fold]
enable = true
level = 1
